
gpu609-07 pinned to port 42791 on vsc509-03-l
To connect to the compute node gpu609-07 on IBEX running your jupyter notebook server, you need to run following two commands in a terminal 1.
Command to create ssh tunnel from you workstation/laptop to glogin:

ssh -L 42791:gpu609-07.ibex.kaust.edu.sa:42791 xiex@glogin.ibex.kaust.edu.sa

Copy the link provided below by jupyter-server and replace the NODENAME with localhost before pasting it in your browser on your workstation/laptop.

[I 2025-03-15 11:55:33.929 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-03-15 11:55:33.935 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-03-15 11:55:33.941 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-03-15 11:55:35.919 ServerApp] notebook_shim | extension was successfully linked.
[I 2025-03-15 11:55:35.954 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-03-15 11:55:35.957 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-03-15 11:55:35.960 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-03-15 11:55:35.970 LabApp] JupyterLab extension loaded from /ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/jupyterlab
[I 2025-03-15 11:55:35.970 LabApp] JupyterLab application directory is /ibex/user/xiex/conda-environments/llm4amr/share/jupyter/lab
[I 2025-03-15 11:55:35.970 LabApp] Extension Manager is 'pypi'.
[I 2025-03-15 11:55:36.016 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-03-15 11:55:36.017 ServerApp] Serving notebooks from local directory: /ibex/user/xiex/ide/LLM4AMR/llm_final_codes
[I 2025-03-15 11:55:36.017 ServerApp] Jupyter Server 2.15.0 is running at:
[I 2025-03-15 11:55:36.017 ServerApp] http://gpu609-07.ibex.kaust.edu.sa:42791/lab?token=683acf0494a52f6ce0e4103d957bd6f2fa4eeab954bd42ba
[I 2025-03-15 11:55:36.017 ServerApp]     http://127.0.0.1:42791/lab?token=683acf0494a52f6ce0e4103d957bd6f2fa4eeab954bd42ba
[I 2025-03-15 11:55:36.017 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2025-03-15 11:55:36.035 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/xiex/.local/share/jupyter/runtime/jpserver-466410-open.html
    Or copy and paste one of these URLs:
        http://gpu609-07.ibex.kaust.edu.sa:42791/lab?token=683acf0494a52f6ce0e4103d957bd6f2fa4eeab954bd42ba
        http://127.0.0.1:42791/lab?token=683acf0494a52f6ce0e4103d957bd6f2fa4eeab954bd42ba
[I 2025-03-15 11:55:36.128 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[E 2025-03-15 11:59:58.100 ServerApp] Uncaught exception GET /lab/api/settings?1742029196387 (10.152.70.16)
    HTTPServerRequest(protocol='http', host='gpu609-07.ibex.kaust.edu.sa:42791', method='GET', uri='/lab/api/settings?1742029196387', version='HTTP/1.1', remote_ip='10.152.70.16')
    Traceback (most recent call last):
      File "/home/xiex/.local/lib/python3.9/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
    tornado.iostream.StreamClosedError: Stream is closed
[E 2025-03-15 11:59:58.198 ServerApp] Uncaught exception GET /lab/api/settings?1742029196389 (10.152.70.16)
    HTTPServerRequest(protocol='http', host='gpu609-07.ibex.kaust.edu.sa:42791', method='GET', uri='/lab/api/settings?1742029196389', version='HTTP/1.1', remote_ip='10.152.70.16')
    Traceback (most recent call last):
      File "/home/xiex/.local/lib/python3.9/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
    tornado.iostream.StreamClosedError: Stream is closed
[W 2025-03-15 12:00:09.967 LabApp] Could not determine jupyterlab build status without nodejs
[I 2025-03-15 12:01:27.267 ServerApp] Creating new notebook in 
[I 2025-03-15 12:01:32.618 ServerApp] Kernel started: a163c61b-92ef-44f5-a330-a40b2555a888
[I 2025-03-15 12:01:34.351 ServerApp] Connecting to kernel a163c61b-92ef-44f5-a330-a40b2555a888.
[I 2025-03-15 12:01:35.913 ServerApp] Starting buffering for a163c61b-92ef-44f5-a330-a40b2555a888:c1cf5b1f-b45f-46f5-bf60-94a3749072f2
[I 2025-03-15 12:01:36.457 ServerApp] Connecting to kernel a163c61b-92ef-44f5-a330-a40b2555a888.
[I 2025-03-15 12:01:38.204 ServerApp] Connecting to kernel a163c61b-92ef-44f5-a330-a40b2555a888.
[I 2025-03-15 12:02:36.262 ServerApp] Saving file at /llm_classification.py
[I 2025-03-15 12:03:31.389 ServerApp] Saving file at /Untitled.ipynb
[I 2025-03-15 12:04:07.386 ServerApp] Kernel interrupted: a163c61b-92ef-44f5-a330-a40b2555a888
[I 2025-03-15 12:04:09.236 ServerApp] Kernel interrupted: a163c61b-92ef-44f5-a330-a40b2555a888
[I 2025-03-15 12:04:39.247 ServerApp] Kernel interrupted: a163c61b-92ef-44f5-a330-a40b2555a888
[I 2025-03-15 12:05:33.059 ServerApp] Saving file at /Untitled.ipynb
[I 2025-03-15 12:06:04.250 ServerApp] Saving file at /Untitled.ipynb
[W 2025-03-15 12:06:15.647 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029574697 (6236830ad48147af84fb8f507226c050@10.152.70.16) 1.68ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/test.ipynb
[W 2025-03-15 12:06:15.648 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029574697 (10.152.70.16): No such file or directory: qwen/Qwen2-1___5B-Instruct
[W 2025-03-15 12:06:41.468 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029601103 (6236830ad48147af84fb8f507226c050@10.152.70.16) 1.70ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/test.ipynb
[W 2025-03-15 12:06:41.468 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029601103 (10.152.70.16): No such file or directory: qwen/Qwen2-1___5B-Instruct
[W 2025-03-15 12:06:42.020 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029601672 (6236830ad48147af84fb8f507226c050@10.152.70.16) 1.10ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/test.ipynb
[W 2025-03-15 12:06:42.020 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029601672 (10.152.70.16): No such file or directory: qwen/Qwen2-1___5B-Instruct
[W 2025-03-15 12:06:42.557 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029602217 (6236830ad48147af84fb8f507226c050@10.152.70.16) 1.73ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/test.ipynb
[W 2025-03-15 12:06:42.557 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029602217 (10.152.70.16): No such file or directory: qwen/Qwen2-1___5B-Instruct
[I 2025-03-15 12:07:45.292 ServerApp] Kernel interrupted: a163c61b-92ef-44f5-a330-a40b2555a888
[I 2025-03-15 12:07:53.482 ServerApp] Saving file at /test.ipynb
[W 2025-03-15 12:08:22.893 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029702539 (6236830ad48147af84fb8f507226c050@10.152.70.16) 1.67ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/test.ipynb
[W 2025-03-15 12:08:22.893 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029702539 (10.152.70.16): No such file or directory: qwen/Qwen2-1___5B-Instruct
[W 2025-03-15 12:08:23.717 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029703091 (6236830ad48147af84fb8f507226c050@10.152.70.16) 1.04ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/test.ipynb
[W 2025-03-15 12:08:23.717 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029703091 (10.152.70.16): No such file or directory: qwen/Qwen2-1___5B-Instruct
[W 2025-03-15 12:08:24.260 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029703911 (6236830ad48147af84fb8f507226c050@10.152.70.16) 1.59ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/test.ipynb
[W 2025-03-15 12:08:24.260 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029703911 (10.152.70.16): No such file or directory: qwen/Qwen2-1___5B-Instruct
[W 2025-03-15 12:09:05.701 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029745339 (6236830ad48147af84fb8f507226c050@10.152.70.16) 1.33ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/test.ipynb
[W 2025-03-15 12:09:05.701 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029745339 (10.152.70.16): No such file or directory: qwen/Qwen2-1___5B-Instruct
[I 2025-03-15 12:09:58.583 ServerApp] Saving file at /test.ipynb
[I 2025-03-15 12:12:01.360 ServerApp] Saving file at /test.ipynb
[W 2025-03-15 12:13:03.386 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029982251 (6236830ad48147af84fb8f507226c050@10.152.70.16) 1.22ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/llm_generation.py
[W 2025-03-15 12:13:03.387 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029982251 (10.152.70.16): No such file or directory: qwen/Qwen2-1___5B-Instruct
[W 2025-03-15 12:13:03.915 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029983560 (6236830ad48147af84fb8f507226c050@10.152.70.16) 1.56ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/llm_generation.py
[W 2025-03-15 12:13:03.915 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029983560 (10.152.70.16): No such file or directory: qwen/Qwen2-1___5B-Instruct
[W 2025-03-15 12:13:05.487 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029984383 (6236830ad48147af84fb8f507226c050@10.152.70.16) 1.11ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/test.ipynb
[W 2025-03-15 12:13:05.488 ServerApp] 404 GET /api/contents/qwen/Qwen2-1___5B-Instruct?content=0&hash=0&1742029984383 (10.152.70.16): No such file or directory: qwen/Qwen2-1___5B-Instruct
[I 2025-03-15 12:14:06.342 ServerApp] Saving file at /test.ipynb
[I 2025-03-15 12:15:28.831 ServerApp] Saving file at /test.ipynb
[I 2025-03-15 12:16:22.559 ServerApp] Saving file at /test.ipynb
[I 2025-03-15 12:16:35.837 ServerApp] Kernel interrupted: a163c61b-92ef-44f5-a330-a40b2555a888
[W 2025-03-15 12:17:26.946 ServerApp] delete /qwen
[W 2025-03-15 12:17:26.947 ServerApp] 400 DELETE /api/contents/qwen?1742030246584 (10.152.70.16): send2trash failed: [Errno 13] Permission denied: b'/ibex/user/.Trash-213161'
[W 2025-03-15 12:17:26.947 ServerApp] wrote error: "send2trash failed: [Errno 13] Permission denied: b'/ibex/user/.Trash-213161'"
    Traceback (most recent call last):
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/send2trash/plat_other.py", line 158, in find_ext_volume_fallback_trash
        check_create(trash_dir)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/send2trash/plat_other.py", line 96, in check_create
        os.makedirs(dir, 0o700)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/os.py", line 225, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: b'/ibex/user/.Trash-213161'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/jupyter_server/services/contents/filemanager.py", line 1030, in delete_file
        send2trash(os_path)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/send2trash/plat_other.py", line 210, in send2trash
        dest_trash = find_ext_volume_trash(topdir)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/send2trash/plat_other.py", line 169, in find_ext_volume_trash
        trash_dir = find_ext_volume_fallback_trash(volume_root)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/send2trash/plat_other.py", line 161, in find_ext_volume_fallback_trash
        raise TrashPermissionError(e.filename)
    send2trash.exceptions.TrashPermissionError: [Errno 13] Permission denied: b'/ibex/user/.Trash-213161'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/xiex/.local/lib/python3.9/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/jupyter_server/services/contents/handlers.py", line 336, in delete
        await ensure_async(cm.delete(path))
      File "/home/xiex/.local/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/jupyter_server/services/contents/manager.py", line 900, in delete
        await self.delete_file(path)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/jupyter_server/services/contents/filemanager.py", line 1032, in delete_file
        raise web.HTTPError(400, "send2trash failed: %s" % e) from e
    tornado.web.HTTPError: HTTP 400: Bad Request (send2trash failed: [Errno 13] Permission denied: b'/ibex/user/.Trash-213161')
[W 2025-03-15 12:17:26.963 ServerApp] 400 DELETE /api/contents/qwen?1742030246584 (6236830ad48147af84fb8f507226c050@10.152.70.16) 18.33ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/test.ipynb
[I 2025-03-15 12:18:26.673 ServerApp] Saving file at /test.ipynb
[I 2025-03-15 12:19:04.426 ServerApp] Kernel interrupted: a163c61b-92ef-44f5-a330-a40b2555a888
[I 2025-03-15 12:20:30.115 ServerApp] Saving file at /test.ipynb
[I 2025-03-15 12:21:38.384 ServerApp] Saving file at /test.ipynb
[I 2025-03-15 12:23:40.286 ServerApp] Saving file at /test.ipynb
[I 2025-03-15 12:23:55.677 ServerApp] Kernel interrupted: a163c61b-92ef-44f5-a330-a40b2555a888
[I 2025-03-15 12:25:44.698 ServerApp] Saving file at /test.ipynb
[I 2025-03-15 12:26:17.816 ServerApp] Creating new directory in 
[W 2025-03-15 12:27:03.866 ServerApp] delete /output_my_training_classification_ubl_March_5_final_complete
[W 2025-03-15 12:27:03.867 ServerApp] 400 DELETE /api/contents/output_my_training_classification_ubl_March_5_final_complete?1742030823488 (10.152.70.16): send2trash failed: [Errno 13] Permission denied: b'/ibex/user/.Trash-213161'
[W 2025-03-15 12:27:03.867 ServerApp] wrote error: "send2trash failed: [Errno 13] Permission denied: b'/ibex/user/.Trash-213161'"
    Traceback (most recent call last):
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/send2trash/plat_other.py", line 158, in find_ext_volume_fallback_trash
        check_create(trash_dir)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/send2trash/plat_other.py", line 96, in check_create
        os.makedirs(dir, 0o700)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/os.py", line 225, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: b'/ibex/user/.Trash-213161'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/jupyter_server/services/contents/filemanager.py", line 1030, in delete_file
        send2trash(os_path)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/send2trash/plat_other.py", line 210, in send2trash
        dest_trash = find_ext_volume_trash(topdir)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/send2trash/plat_other.py", line 169, in find_ext_volume_trash
        trash_dir = find_ext_volume_fallback_trash(volume_root)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/send2trash/plat_other.py", line 161, in find_ext_volume_fallback_trash
        raise TrashPermissionError(e.filename)
    send2trash.exceptions.TrashPermissionError: [Errno 13] Permission denied: b'/ibex/user/.Trash-213161'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/xiex/.local/lib/python3.9/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/jupyter_server/services/contents/handlers.py", line 336, in delete
        await ensure_async(cm.delete(path))
      File "/home/xiex/.local/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/jupyter_server/services/contents/manager.py", line 900, in delete
        await self.delete_file(path)
      File "/ibex/user/xiex/conda-environments/llm4amr/lib/python3.9/site-packages/jupyter_server/services/contents/filemanager.py", line 1032, in delete_file
        raise web.HTTPError(400, "send2trash failed: %s" % e) from e
    tornado.web.HTTPError: HTTP 400: Bad Request (send2trash failed: [Errno 13] Permission denied: b'/ibex/user/.Trash-213161')
[W 2025-03-15 12:27:03.871 ServerApp] 400 DELETE /api/contents/output_my_training_classification_ubl_March_5_final_complete?1742030823488 (6236830ad48147af84fb8f507226c050@10.152.70.16) 5.86ms referer=http://gpu609-07.ibex.kaust.edu.sa:42791/lab/workspaces/auto-G/tree/test.ipynb
[I 2025-03-15 12:27:08.207 ServerApp] Creating new directory in 
[I 2025-03-15 12:27:12.346 ServerApp] Creating new notebook in 
[I 2025-03-15 12:27:15.333 ServerApp] Kernel started: 475780af-5220-4059-af95-bdb508b04ada
[I 2025-03-15 12:27:16.999 ServerApp] Connecting to kernel 475780af-5220-4059-af95-bdb508b04ada.
[I 2025-03-15 12:29:16.626 ServerApp] Saving file at /Untitled.ipynb
[W 2025-03-15 13:52:36.459 ServerApp] WebSocket ping timeout after 119467 ms.
[I 2025-03-15 13:52:41.464 ServerApp] Starting buffering for a163c61b-92ef-44f5-a330-a40b2555a888:0f45cb92-15f8-4ef9-80a3-fecde7f65155
[W 2025-03-15 13:52:47.002 ServerApp] WebSocket ping timeout after 118673 ms.
[I 2025-03-15 13:52:52.003 ServerApp] Starting buffering for 475780af-5220-4059-af95-bdb508b04ada:5ba5b8c9-7966-4e79-8a6b-48fc5b7435c2
slurmstepd: error: *** JOB 37929702 ON gpu609-07 CANCELLED AT 2025-03-15T18:55:57 DUE TO TIME LIMIT ***
